.TH "ArbreRenduINF2990" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArbreRenduINF2990 \- Classe qui représente l'arbre de rendu spécifique au projet de INF2990\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ArbreRenduINF2990\&.h>\fP
.PP
Inherits \fBArbreRendu\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArbreRenduINF2990\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~ArbreRenduINF2990\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "void \fBinitialiser\fP ()"
.br
.RI "\fIInitialise l'arbre de rendu à son état initial\&. \fP"
.ti -1c
.RI "void \fBchargerZone\fP ()"
.br
.RI "\fICharge le fichier de sauvegarde présentement assigné à l'arbre de rendu\&. \fP"
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBNOM_ROBOT\fP { 'robot' }"
.br
.RI "\fILa chaîne représentant le type du robot\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_TABLE\fP { 'table' }"
.br
.RI "\fILa chaîne représentant le type de la table\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_POTEAU\fP { 'poteau' }"
.br
.RI "\fILa chaîne représentant le type des poteaux\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_MUR\fP { 'mur' }"
.br
.RI "\fILa chaîne représentant le type des murs\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_LIGNENOIRE\fP { 'ligneNoire' }"
.br
.RI "\fILa chaîne représentant le type des lignes\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_SEGMENT\fP { 'segment' }"
.br
.RI "\fILa chaîne représentant le type des segments\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_DUPLICATION\fP { 'duplication' }"
.br
.RI "\fILa chaîne représentant le type des duplications\&. \fP"
.ti -1c
.RI "static const std::string \fBNOM_JONCTION\fP { 'jonction' }"
.br
.RI "\fILa chaîne représentant le type du point de départ\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Classe qui représente l'arbre de rendu spécifique au projet de INF2990\&. 

Cette classe s'occupe de configurer les usines des noeuds qui seront utilisés par le projet\&.
.PP
\fBAuthor:\fP
.RS 4
Martin Bisson 
.RE
.PP
\fBDate:\fP
.RS 4
2007-03-23 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
