.TH "Sources/DLL/Arbre/ArbreRenduINF2990.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/ArbreRenduINF2990.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ArbreRendu\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'rapidjson\\document\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArbreRenduINF2990\fP"
.br
.RI "\fIClasse qui représente l'arbre de rendu spécifique au projet de INF2990\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Martin Bisson 
.RE
.PP
\fBDate:\fP
.RS 4
2007-03-23 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
