.TH "Sources/DLL/Arbre/ArbreRendu.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/ArbreRendu.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NoeudComposite\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'UsineNoeud\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArbreRendu\fP"
.br
.RI "\fIClasse d'arbre de rendu qui contient la racine de l'arbre de rendu avec les usines qui permettent d'ajouter des noeuds à cet arbre\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Martin Bisson 
.RE
.PP
\fBDate:\fP
.RS 4
2007-01-28 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
