.TH "BancTests" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BancTests \- Banc de tests qui permet d'exécuter tous les tests unitaires\&. C'est une classe singleton\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BancTests\&.h>\fP
.PP
Inherits Singleton< BancTests >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBexecuter\fP ()"
.br
.RI "\fIExécuter tous les tests unitaires\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Banc de tests qui permet d'exécuter tous les tests unitaires\&. C'est une classe singleton\&. 


.PP
\fBAuthor:\fP
.RS 4
Julien Gascon-Samson 
.RE
.PP
\fBDate:\fP
.RS 4
2011-07-16 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
