.TH "Sources/DLL/Tests/ConfigSceneTest.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Tests/ConfigSceneTest.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cppunit/extensions/HelperMacros\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigSceneTest\fP"
.br
.RI "\fIClasse de test cppunit pour tester le bon fonctionnement des méthodes de la classe \fBConfigScene\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Julien Gascon-Samson 
.RE
.PP
\fBDate:\fP
.RS 4
2011-07-16 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
