.TH "Sources/DLL/Tests/ConfigSceneTest.cpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Tests/ConfigSceneTest.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ConfigSceneTest\&.h'\fP
.br
\fC#include 'ConfigScene\&.h'\fP
.br
\fC#include 'FacadeModele\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCPPUNIT_TEST_SUITE_REGISTRATION\fP (\fBConfigSceneTest\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Julien Gascon-Samson 
.RE
.PP
\fBDate:\fP
.RS 4
2011-07-16 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
