.TH "Sources/DLL/Configuration/ConfigScene.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Configuration/ConfigScene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Singleton\&.h'\fP
.br
\fC#include 'tinyxml2\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigScene\fP"
.br
.RI "\fILes variables de configuration de la classe CScene\&. C'est une classe singleton\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jean-François Pérusse 
.RE
.PP
\fBDate:\fP
.RS 4
2007-01-10 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
