.TH "EtatRotation" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatRotation \- État représentant la rotation d'un objet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EtatRotation\&.h>\fP
.PP
Inherits \fBEtatAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEtatRotation\fP ()"
.br
.ti -1c
.RI "virtual \fB~EtatRotation\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheEnfonce\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheRelache\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererMouvementSouris\fP (const int &x, const int &y)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBreinitialiser\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
État représentant la rotation d'un objet\&. 


.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
