.TH "EtatSelection" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatSelection \- État représentant la sélection d'un objet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EtatSelection\&.h>\fP
.PP
Inherits \fBEtatAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEtatSelection\fP ()"
.br
.ti -1c
.RI "virtual \fB~EtatSelection\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheRelache\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererMouvementSouris\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "void \fBgererClicGauche\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "void \fBgererDragGauche\fP (const int &xAvant, const int &yAvant, const int &xApres, const int &yApres)"
.br
.ti -1c
.RI "void \fBgererToucheControlEnfoncee\fP ()"
.br
.ti -1c
.RI "void \fBgererToucheControlRelachee\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
État représentant la sélection d'un objet\&. 


.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
