.TH "EtatCreationMur" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EtatCreationMur \- État représentant la creation d'un mur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EtatCreationMur\&.h>\fP
.PP
Inherits \fBEtatAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEtatCreationMur\fP ()"
.br
.ti -1c
.RI "virtual \fB~EtatCreationMur\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheEnfonce\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheRelache\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererMouvementSouris\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererToucheEchappe\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererPositionCurseurConcret\fP (const bool &positionEstSurTable)"
.br
.ti -1c
.RI "virtual void \fBassignerSymboleCurseur\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
État représentant la creation d'un mur\&. 


.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
