.TH "Sources/DLL/MachineAEtats/EtatAbstrait.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/MachineAEtats/EtatAbstrait.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'VisiteurAbstrait\&.h'\fP
.br
\fC#include 'glm\\glm\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEtatAbstrait\fP"
.br
.RI "\fIClasse de base pour chaque état\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEtat\fP { \fBSELECTION\fP, \fBDEPLACEMENT\fP, \fBROTATION\fP, \fBMISE_A_ECHELLE\fP, \fBDUPLICATION\fP, \fBCREATION_POTEAU\fP, \fBCREATION_MUR\fP, \fBCREATION_LIGNE_NOIRE\fP, \fBZOOM\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4

.RE
.PP
\fBDate:\fP
.RS 4
2016-01-22 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
