.TH "Sources/DLL/MachineAEtats/EtatLoupe.cpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/MachineAEtats/EtatLoupe.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FacadeModele\&.h'\fP
.br
\fC#include 'Vue\&.h'\fP
.br
\fC#include 'EtatLoupe\&.h'\fP
.br
\fC#include 'AideGl\&.h'\fP
.br
\fC#include 'OpenGL_Programme\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Philippe Marcotte et Camille Gendreau 
.RE
.PP
\fBDate:\fP
.RS 4
2016-05-19 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
