.TH "Sources/DLL/MachineAEtats/EtatTypes.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/MachineAEtats/EtatTypes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'EtatCreationLigne\&.h'\fP
.br
\fC#include 'EtatCreationMur\&.h'\fP
.br
\fC#include 'EtatCreationPoteau\&.h'\fP
.br
\fC#include 'EtatDeplacement\&.h'\fP
.br
\fC#include 'EtatDuplication\&.h'\fP
.br
\fC#include 'EtatMiseAEchelle\&.h'\fP
.br
\fC#include 'EtatRotation\&.h'\fP
.br
\fC#include 'EtatSelection\&.h'\fP
.br
\fC#include 'EtatLoupe\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Ulric Villeneuve et Simon-Pierre Desjardins 
.RE
.PP
\fBDate:\fP
.RS 4
2016-01-22 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
