.TH "Sources/InterfaceGraphique/FormulairesSysFichiers/ExplorateurSauvegarde.cs" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/InterfaceGraphique/FormulairesSysFichiers/ExplorateurSauvegarde.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterfaceGraphique\&.ExplorateurSauvegarde\fP"
.br
.RI "\fIFormulaire permettant à l'utilisateur de choisir ou créer dans quel fichier sauvegarder la zone qu'il a créée\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Philippe Marcotte 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-13 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
