.TH "Sources/DLL/Application/FacadeModele.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Application/FacadeModele.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Vue\&.h'\fP
.br
\fC#include 'ArbreRenduINF2990\&.h'\fP
.br
\fC#include 'EtatAbstrait\&.h'\fP
.br
\fC#include 'ModeAbstrait\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFacadeModele\fP"
.br
.RI "\fIClasse qui constitue une interface (une façade) sur l'ensemble du modèle et des classes qui le composent\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
DGI 
.RE
.PP
\fBDate:\fP
.RS 4
2005-06-15 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
