.TH "Sources/DLL/Interface/FacadeInterfaceNative.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Interface/FacadeInterfaceNative.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br
\fC#include <Windowsx\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__declspec\fP (dllexport) void __cdecl initialiserOpenGL(int *handle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBhauteur\fP"
.br
.ti -1c
.RI "int \fBlongueur\fP"
.br
.ti -1c
.RI "WPARAM \fBwParam\fP"
.br
.ti -1c
.RI "WPARAM LPARAM \fBlParam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
INF2990 
.RE
.PP
\fBDate:\fP
.RS 4
2014-08-16 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
