.TH "InterfaceGraphique" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExplorateurOuverture\fP"
.br
.ti -1c
.RI "class \fBExplorateurSauvegarde\fP"
.br
.RI "\fIFormulaire permettant à l'utilisateur de choisir ou créer dans quel fichier sauvegarder la zone qu'il a créée\&. \fP"
.ti -1c
.RI "class \fBFonctionsNatives\fP"
.br
.ti -1c
.RI "class \fBMenuEditionNouveau\fP"
.br
.ti -1c
.RI "class \fBNouveauFichier\fP"
.br
.ti -1c
.RI "class \fBPopOutInterface\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEtat\fP { \fBSELECTION\fP, \fBDEPLACEMENT\fP, \fBROTATION\fP, \fBMISE_A_ECHELLE\fP, \fBDUPLICATION\fP, \fBCREATION_POTEAU\fP, \fBCREATION_MUR\fP, \fBCREATION_LIGNE_NOIRE\fP, \fBZOOM\fP }"
.br
.ti -1c
.RI "enum \fBMode\fP { \fBMENU_PRINCIPAL\fP, \fBSIMULATION\fP, \fBEDITION\fP, \fBCONFIGURE\fP, \fBTEST\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
