.TH "InterfaceGraphique.MenuEditionNouveau" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.MenuEditionNouveau \- 
.SH SYNOPSIS
.br
.PP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void InterfaceGraphique\&.MenuEditionNouveau\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
