.TH "InterfaceGraphique.ExplorateurSauvegarde" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.ExplorateurSauvegarde \- Formulaire permettant à l'utilisateur de choisir ou créer dans quel fichier sauvegarder la zone qu'il a créée\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExplorateurSauvegarde\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBcheminFichier\fP"
.br
.RI "\fIChemin vers le fichier que l'utilisateur a sélectionné \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Formulaire permettant à l'utilisateur de choisir ou créer dans quel fichier sauvegarder la zone qu'il a créée\&. 


.PP
\fBAuthor:\fP
.RS 4
Philippe Marcotte 
.RE
.PP
\fBDate:\fP
.RS 4
2016-2-13 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "public InterfaceGraphique\&.ExplorateurSauvegarde\&.ExplorateurSauvegarde ()\fC [inline]\fP"
Constructeur par défaut Initialise les composantes du formulaires et popule l'arbre de dossiers\&.
.PP
\fBReturns:\fP
.RS 4
Aucune 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void InterfaceGraphique\&.ExplorateurSauvegarde\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "String InterfaceGraphique\&.ExplorateurSauvegarde\&.cheminFichier"

.PP
Chemin vers le fichier que l'utilisateur a sélectionné 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
