.TH "InterfaceGraphique.ExplorateurOuverture" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.ExplorateurOuverture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExplorateurOuverture\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBcheminFichier\fP"
.br
.RI "\fIChemin vers le fichier que l'utilisateur a sélectionné \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public InterfaceGraphique\&.ExplorateurOuverture\&.ExplorateurOuverture ()\fC [inline]\fP"
Constructeur par défaut Initialise les composantes du formulaires et popule l'arbre de dossiers\&.
.PP
\fBReturns:\fP
.RS 4
Aucune 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void InterfaceGraphique\&.ExplorateurOuverture\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "String InterfaceGraphique\&.ExplorateurOuverture\&.cheminFichier"

.PP
Chemin vers le fichier que l'utilisateur a sélectionné 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
