.TH "InterfaceGraphique.Properties" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.Properties \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "\fIA strongly-typed resource class, for looking up localized strings, etc\&. \fP"
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
