.TH "InterfaceGraphique.Window" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.Window \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form, and IMessageFilter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBarreterToutMessage\fP ()"
.br
.ti -1c
.RI "bool \fBPreFilterMessage\fP (ref Message m)"
.br
.ti -1c
.RI "\fBWindow\fP ()"
.br
.ti -1c
.RI "void \fBInitialiserAnimation\fP ()"
.br
.ti -1c
.RI "void \fBMettreAJour\fP (double tempsInterAffichage)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fINettoyage des ressources utilisées\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void InterfaceGraphique\&.Window\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Nettoyage des ressources utilisées\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true si les ressources managées doivent être supprimées ; sinon, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
