.TH "InterfaceGraphique.FonctionsNatives.Message" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.FonctionsNatives.Message \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBhWnd\fP"
.br
.ti -1c
.RI "uint \fBMsg\fP"
.br
.ti -1c
.RI "IntPtr \fBwParam\fP"
.br
.ti -1c
.RI "IntPtr \fBlParam\fP"
.br
.ti -1c
.RI "uint \fBTime\fP"
.br
.ti -1c
.RI "System\&.Drawing\&.Point \fBPoint\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
