.TH "InterfaceGraphique.NouveauFichier" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceGraphique.NouveauFichier \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNouveauFichier\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBnomFichier\fP"
.br
.RI "\fINom du fichier à créer \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "public InterfaceGraphique\&.NouveauFichier\&.NouveauFichier ()\fC [inline]\fP"
Constructeur par défaut Initialise les composantes du formulaires\&.
.PP
\fBReturns:\fP
.RS 4
Aucune 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void InterfaceGraphique\&.NouveauFichier\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string InterfaceGraphique\&.NouveauFichier\&.nomFichier"

.PP
Nom du fichier à créer 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
