.TH "Sources/DLL/MachineAModes/ModeSimulation.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/MachineAModes/ModeSimulation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ModeAbstrait\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'glm\\glm\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModeSimulation\fP"
.br
.RI "\fIClasse qui représente le mode simulation de notre machine à modes\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-02 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
