.TH "Sources/DLL/MachineAModes/ModeTest.cpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/MachineAModes/ModeTest.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ModeTest\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'Utilitaire\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'FacadeModele\&.h'\fP
.br
\fC#include 'Vue\&.h'\fP
.br
\fC#include 'Projection\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-02 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
