.TH "ModeConfigure" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModeConfigure \- Classe qui représente le mode configure de notre machine à modes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModeConfigure\&.h>\fP
.PP
Inherits \fBModeAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModeConfigure\fP ()"
.br
.ti -1c
.RI "virtual \fB~ModeConfigure\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Classe qui représente le mode configure de notre machine à modes\&. 

Cette classe s'occupe d'implémenter les fonctions du mode configure
.PP
\fBAuthor:\fP
.RS 4
Simon-Pierre Desjardins 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-14 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
