.TH "Sources/DLL/MachineAModes/ModeTypes.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/MachineAModes/ModeTypes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ModeConfigure\&.h'\fP
.br
\fC#include 'ModeEdition\&.h'\fP
.br
\fC#include 'ModeMenuPrincipal\&.h'\fP
.br
\fC#include 'ModeSimulation\&.h'\fP
.br
\fC#include 'ModeTest\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-02 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
