.TH "ModeEdition" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModeEdition \- Classe qui représente le mode edition de notre machine à modes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModeEdition\&.h>\fP
.PP
Inherits \fBModeAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModeEdition\fP ()"
.br
.ti -1c
.RI "virtual \fB~ModeEdition\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererTouchePlus\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheMoins\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheEchappe\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheC\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheD\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheE\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheR\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheS\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheT\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheZ\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheCTRLavecS\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheCTRLavecN\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheCTRLavecO\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererTouche1\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererTouche2\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererFlecheGauche\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererFlecheBas\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererFlecheHaut\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererFlecheDroit\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheControlEnfoncee\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheControlRelachee\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheAltEnfoncee\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererToucheAltRelachee\fP ()"
.br
.ti -1c
.RI "virtual void \fBgererClicDroitEnfonce\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererClicDroitRelache\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheEnfonce\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererClicGaucheRelache\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererMouvementSouris\fP (const int &x, const int &y)"
.br
.ti -1c
.RI "virtual void \fBgererMoletteSouris\fP (const int &delta)"
.br
.ti -1c
.RI "virtual void \fBgererToucheSupprimer\fP ()"
.br
.ti -1c
.RI "virtual void \fBsauvegarder\fP ()"
.br
.ti -1c
.RI "virtual void \fBcharger\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBVisiteurSuppression\fP > \fBvisiteurSuppression_\fP"
.br
.ti -1c
.RI "int \fBancienSourisX_\fP { 0 }"
.br
.ti -1c
.RI "int \fBancienSourisY_\fP { 0 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe qui représente le mode edition de notre machine à modes\&. 


.PP
\fBAuthor:\fP
.RS 4
Simon-Pierre Desjardins 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-14
.RE
.PP
Cette classe s'occupe d'implémenter les fonctions du mode edition 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
