.TH "Sources/DLL/Arbre/Noeuds/NoeudJonction.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/Noeuds/NoeudJonction.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NoeudComposite\&.h'\fP
.br
\fC#include 'GL/glew\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNoeudJonction\fP"
.br
.RI "\fINoeud de l'objet rendu servant à la liaison de segments de la ligne noire\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Camille Gendreau 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-11 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
