.TH "NoeudJonction" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoeudJonction \- Noeud de l'objet rendu servant à la liaison de segments de la ligne noire\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoeudJonction\&.h>\fP
.PP
Inherits \fBNoeudAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoeudJonction\fP (const std::string &typeNoeud)"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fB~NoeudJonction\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBafficherConcret\fP () const "
.br
.RI "\fIAffiche la table\&. \fP"
.ti -1c
.RI "virtual void \fBaccepterVisiteur\fP (\fBVisiteurAbstrait\fP *visiteur)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Noeud de l'objet rendu servant à la liaison de segments de la ligne noire\&. 


.PP
\fBAuthor:\fP
.RS 4
Camille Gendreau 
.RE
.PP
\fBDate:\fP
.RS 4
2007-01-24 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
