.TH "NoeudRobot" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoeudRobot \- Classe qui représente le robot du premier projet intégrateur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoeudRobot\&.h>\fP
.PP
Inherits \fBNoeudComposite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoeudRobot\fP (const std::string &typeNoeud)"
.br
.RI "\fIConstructeur à partir du type du noeud\&. \fP"
.ti -1c
.RI "\fB~NoeudRobot\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBafficherConcret\fP () const "
.br
.RI "\fIAffiche le robot\&. \fP"
.ti -1c
.RI "virtual void \fBaccepterVisiteur\fP (\fBVisiteurAbstrait\fP *visiteur)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Classe qui représente le robot du premier projet intégrateur\&. 


.PP
\fBAuthor:\fP
.RS 4
Martin Paradis 
.RE
.PP
\fBDate:\fP
.RS 4
2015-08-30 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
