.TH "Sources/DLL/Arbre/Noeuds/NoeudRobot.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/Noeuds/NoeudRobot.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NoeudComposite\&.h'\fP
.br
\fC#include 'GL/glew\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNoeudRobot\fP"
.br
.RI "\fIClasse qui représente le robot du premier projet intégrateur\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Martin Paradis 
.RE
.PP
\fBDate:\fP
.RS 4
2015-08-30 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
