.TH "Sources/DLL/Arbre/Noeuds/NoeudPoteau.cpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/Noeuds/NoeudPoteau.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NoeudPoteau\&.h'\fP
.br
\fC#include 'Utilitaire\&.h'\fP
.br
\fC#include 'GL/glew\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Modele3D\&.h'\fP
.br
\fC#include 'OpenGL_VBO\&.h'\fP
.br
\fC#include 'VisiteurAbstrait\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Camille Gendreau 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-11 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0
.RE
.PP
\fBAuthor:\fP
.RS 4
Philippe Marcotte et Camille Gendreau 
.RE
.PP
\fBDate:\fP
.RS 4
2011-05-19 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
