.TH "NoeudDuplication" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoeudDuplication \- Noeud qui représente une duplication lors de l'utilisation de l'outil duplication\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoeudDuplication\&.h>\fP
.PP
Inherits \fBNoeudComposite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoeudDuplication\fP (const std::string &typeNoeud)"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fB~NoeudDuplication\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBafficherConcret\fP () const "
.br
.RI "\fIAffiche la table\&. \fP"
.ti -1c
.RI "std::shared_ptr< \fBNoeudAbstrait\fP > \fBobtenirDuplication\fP (const int &indice)"
.br
.RI "\fIObtenir le pointeur intelligent d'un noeud dans le but de faire un transfert de possession\&. \fP"
.ti -1c
.RI "virtual void \fBaccepterVisiteur\fP (\fBVisiteurAbstrait\fP *visiteur)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Noeud qui représente une duplication lors de l'utilisation de l'outil duplication\&. 


.PP
\fBAuthor:\fP
.RS 4
Olivier St-Amour 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
