.TH "Sources/DLL/Arbre/Noeuds/NoeudComposite.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/Noeuds/NoeudComposite.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NoeudAbstrait\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNoeudComposite\fP"
.br
.RI "\fIImplantation d'un noeud du patron composite qui peut posséder des enfants\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
DGI-INF2990 
.RE
.PP
\fBDate:\fP
.RS 4
2007-01-25 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
