.TH "NoeudLigne" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoeudLigne \- Noeud de l'objet englobant tous les segments et jonctions d'une ligne noire\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoeudLigne\&.h>\fP
.PP
Inherits \fBNoeudComposite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoeudLigne\fP (const std::string &typeNoeud)"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fB~NoeudLigne\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBafficherConcret\fP () const "
.br
.RI "\fIAffiche la table\&. \fP"
.ti -1c
.RI "virtual void \fBaccepterVisiteur\fP (\fBVisiteurAbstrait\fP *visiteur)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Noeud de l'objet englobant tous les segments et jonctions d'une ligne noire\&. 

Noeud des murs servant d'obstacles au robot\&.
.PP
\fBAuthor:\fP
.RS 4
.RE
.PP
\fBDate:\fP
.RS 4
2016-01-20
.RE
.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-01-20 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
