.TH "Sources/DLL/Arbre/Noeuds/NoeudAbstrait.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/Noeuds/NoeudAbstrait.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GL/glew\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include 'Utilitaire\&.h'\fP
.br
\fC#include 'glm\\glm\&.hpp'\fP
.br
\fC#include 'rapidjson\\writer\&.h'\fP
.br
\fC#include 'rapidjson\\document\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNoeudAbstrait\fP"
.br
.RI "\fIClasse de base du patron composite utilisée pour créer l'arbre de rendu\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmodele\fP"
.br
.RI "\fIDéclarations avancées pour contenir un pointeur vers un modèle3D et son storage\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
DGI-INF2990 
.RE
.PP
\fBDate:\fP
.RS 4
2007-01-24 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
