.TH "NoeudAbstraitTest" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoeudAbstraitTest \- Classe de test cppunit pour tester le bon fonctionnement des méthodes de la classe \fBNoeudAbstrait\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NoeudAbstraitTest\&.h>\fP
.PP
Inherits TestFixture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.RI "\fITraitement à effectuer pour initialiser cette suite de tests\&. \fP"
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.RI "\fITraitement à effectuer pour 'finaliser' cette suite de tests\&. \fP"
.ti -1c
.RI "void \fBtestPositionRelative\fP ()"
.br
.RI "\fICas de test: écriture/lecture de la position relative\&. \fP"
.ti -1c
.RI "void \fBtestType\fP ()"
.br
.RI "\fICas de test: type de noeud\&. \fP"
.ti -1c
.RI "void \fBtestSelection\fP ()"
.br
.RI "\fICas de test: définition/obtention des états de sélection du noeud\&. \fP"
.ti -1c
.RI "void \fBtestEnfants\fP ()"
.br
.RI "\fICas de test: s'assurer que le noeud abstrait n'a pas d'enfant\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Classe de test cppunit pour tester le bon fonctionnement des méthodes de la classe \fBNoeudAbstrait\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Julien Gascon-Samson 
.RE
.PP
\fBDate:\fP
.RS 4
2011-07-16 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
