.TH "UsineAbstraite" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsineAbstraite \- Classe de base abstraite des usines qui seront utilisées pour créer les différents noeuds de l'arbre de rendu\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UsineNoeud\&.h>\fP
.PP
Inherited by \fBUsineNoeud< Noeud >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< \fBNoeudAbstrait\fP > \fBcreerNoeud\fP () const  =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUsineAbstraite\fP (std::string nom)"
.br
.ti -1c
.RI "const std::string & \fBobtenirNom\fP () const "
.br
.RI "\fIRetourne le nom associé à l'usine\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Classe de base abstraite des usines qui seront utilisées pour créer les différents noeuds de l'arbre de rendu\&. 


.PP
\fBAuthor:\fP
.RS 4
Martin Bisson 
.RE
.PP
\fBDate:\fP
.RS 4
2001-01-28 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
