.TH "Sources/DLL/Arbre/Usines/UsineNoeud.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Arbre/Usines/UsineNoeud.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'Modele3D\&.h'\fP
.br
\fC#include 'OpenGL_VBO\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUsineAbstraite\fP"
.br
.RI "\fIClasse de base abstraite des usines qui seront utilisées pour créer les différents noeuds de l'arbre de rendu\&. \fP"
.ti -1c
.RI "class \fBUsineNoeud< Noeud >\fP"
.br
.RI "\fIClass template permettant de créer un type de noeud concret pour l'arbre de rendu\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Martin Bisson 
.RE
.PP
\fBDate:\fP
.RS 4
2007-01-28 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
