.TH "UsineNoeud< Noeud >" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsineNoeud< Noeud > \- Class template permettant de créer un type de noeud concret pour l'arbre de rendu\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UsineNoeud\&.h>\fP
.PP
Inherits \fBUsineAbstraite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~UsineNoeud\fP ()"
.br
.RI "\fIDestructeur vide déclaré virtuel pour les classes dérivées\&. \fP"
.ti -1c
.RI "virtual std::shared_ptr< \fBNoeudAbstrait\fP > \fBcreerNoeud\fP () const  override"
.br
.RI "\fIFonction à surcharger pour la création d'un noeud\&. \fP"
.ti -1c
.RI "\fBUsineNoeud\fP (const std::string &nomUsine, const std::string &nomModele)"
.br
.RI "\fIConstructeur qui prend le nom associé à l'usine\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "modele::Modele3D \fBmodele_\fP"
.br
.RI "\fIModèle 3D correspondant à ce noeud\&. \fP"
.ti -1c
.RI "opengl::VBO \fBvbo_\fP"
.br
.RI "\fIStorage pour le dessin du modèle\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename Noeud>
.br
class UsineNoeud< Noeud >"
Class template permettant de créer un type de noeud concret pour l'arbre de rendu\&. 


.PP
\fBAuthor:\fP
.RS 4
Martin Paradis 
.RE
.PP
\fBDate:\fP
.RS 4
2015-06-24 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
