.TH "Sources/DLL/Visiteur/VisiteurSauvegarde.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Visiteur/VisiteurSauvegarde.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'VisiteurAbstrait\&.h'\fP
.br
\fC#include 'rapidjson\\writer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVisiteurSauvegarde\fP"
.br
.RI "\fICette classe s'occupe de visiter chaque noeuds de l'arbre de rendu pour écrire leurs attributs dans un fichier Json et ainsi, permettre de les charger plus tard\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Philippe Marcotte 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-09 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
