.TH "VisiteurCreationPoteau" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisiteurCreationPoteau \- Visiteur permettant d'initialiser la création d'un poteau\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VisiteurCreationPoteau\&.h>\fP
.PP
Inherits \fBVisiteurAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisiteurCreationPoteau\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~VisiteurCreationPoteau\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBArbreRendu\fP *noeud)"
.br
.RI "\fICreation de poteau sur l'arbre de rendu\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudTable\fP *noeud)"
.br
.RI "\fICreation de poteau sur la table\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Visiteur permettant d'initialiser la création d'un poteau\&. 


.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
