.TH "VisiteurVerificationQuad" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisiteurVerificationQuad \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisiteurAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisiteurVerificationQuad\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~VisiteurVerificationQuad\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "bool \fBobjetsDansZoneSimulation\fP ()"
.br
.RI "\fIObtenir si tous les objets sont dans la zone de simulation\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBArbreRendu\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudTable\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudDuplication\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudPoteau\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudMur\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudLigne\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudSegment\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudDepart\fP *noeud)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
