.TH "VisiteurDuplication" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisiteurDuplication \- Visiteur permettant d'effectuer une duplication d'un objet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VisiteurDuplication\&.h>\fP
.PP
Inherits \fBVisiteurAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisiteurDuplication\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~VisiteurDuplication\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "void \fBassignerEnDuplication\fP (bool enDuplication)"
.br
.ti -1c
.RI "\fBNoeudAbstrait\fP * \fBobtenirDuplication\fP ()"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBArbreRendu\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudTable\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudPoteau\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudMur\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudLigne\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudSegment\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudJonction\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudDuplication\fP *noeud)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Visiteur permettant d'effectuer une duplication d'un objet\&. 


.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
