.TH "Sources/DLL/Visiteur/VisiteurSuppression.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Visiteur/VisiteurSuppression.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'VisiteurAbstrait\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVisiteurSuppression\fP"
.br
.RI "\fIVisiteur permettant d'effectuer la supression d'un objet\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Ulric Villeneuve et Simon-Pierre Desjardins 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-09 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
