.TH "VisiteurSelection" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisiteurSelection \- Visiteur permettant d'effectuer la sélection d'un objet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VisiteurSelection\&.h>\fP
.PP
Inherits \fBVisiteurAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisiteurSelection\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~VisiteurSelection\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBArbreRendu\fP *noeud)"
.br
.RI "\fIParcours du noeudTable\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudTable\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudPoteau\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudMur\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudLigne\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudDepart\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudSegment\fP *noeud)"
.br
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudJonction\fP *noeud)"
.br
.ti -1c
.RI "void \fBassignerControl\fP (bool ctrlAppuye)"
.br
.ti -1c
.RI "void \fBassignerPositionRectElast\fP (const glm::dvec3 &positionPremierClic, const glm::dvec3 &positionDeuxiemeClic)"
.br
.ti -1c
.RI "bool \fBquadEstDansRectangleElastique\fP (const utilitaire::QuadEnglobant &quad)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Visiteur permettant d'effectuer la sélection d'un objet\&. 

Visiteur permettant d'effectuer la vérification de la boite englobante d'un objet pour qu'il soit sur la table\&.
.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
