.TH "Sources/DLL/Visiteur/VisiteurAbstrait.h" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/DLL/Visiteur/VisiteurAbstrait.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'glm\\glm\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVisiteurAbstrait\fP"
.br
.RI "\fIClasse de base du patron visiteur utilisée pour effectuer des manipulations sur l'arbre de rendu\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmodele\fP"
.br
.RI "\fIDéclarations avancées pour contenir un pointeur vers un modèle3D et son storage\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Olivier St-Amour 
.RE
.PP
\fBDate:\fP
.RS 4
2016-01-13 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
