.TH "VisiteurSuppression" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisiteurSuppression \- Visiteur permettant d'effectuer la supression d'un objet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VisiteurSuppression\&.h>\fP
.PP
Inherits \fBVisiteurAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisiteurSuppression\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~VisiteurSuppression\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudTable\fP *noeud)"
.br
.RI "\fIParcours du noeudTable\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Visiteur permettant d'effectuer la supression d'un objet\&. 


.PP
\fBAuthor:\fP
.RS 4
Frédéric Grégoire 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-15 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
