.TH "VisiteurSauvegarde" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisiteurSauvegarde \- Cette classe s'occupe de visiter chaque noeuds de l'arbre de rendu pour écrire leurs attributs dans un fichier Json et ainsi, permettre de les charger plus tard\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VisiteurSauvegarde\&.h>\fP
.PP
Inherits \fBVisiteurAbstrait\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisiteurSauvegarde\fP ()"
.br
.RI "\fIConstructeur par défaut\&. \fP"
.ti -1c
.RI "virtual \fB~VisiteurSauvegarde\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBArbreRendu\fP *noeud)"
.br
.RI "\fISauvegarde en JSON de l'arbre de rendu\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudTable\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudTable\fP\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudPoteau\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudPoteau\fP\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudMur\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudMur\fP\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudLigne\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudLigne\fP\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudSegment\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudSegment\fP\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudDepart\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudDuplication\fP\&. \fP"
.ti -1c
.RI "virtual void \fBvisiter\fP (\fBNoeudJonction\fP *noeud)"
.br
.RI "\fISauvegarde en JSON d'un \fBNoeudDuplication\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Cette classe s'occupe de visiter chaque noeuds de l'arbre de rendu pour écrire leurs attributs dans un fichier Json et ainsi, permettre de les charger plus tard\&. 


.PP
\fBAuthor:\fP
.RS 4
Philippe Marcotte 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-09 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
