.TH "Sources/InterfaceGraphique/Window.cs" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sources/InterfaceGraphique/Window.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterfaceGraphique\&.Window\fP"
.br
.ti -1c
.RI "class \fBInterfaceGraphique\&.FonctionsNatives\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEtat\fP { \fBSELECTION\fP, \fBDEPLACEMENT\fP, \fBROTATION\fP, \fBMISE_A_ECHELLE\fP, \fBDUPLICATION\fP, \fBCREATION_POTEAU\fP, \fBCREATION_MUR\fP, \fBCREATION_LIGNE_NOIRE\fP, \fBZOOM\fP }"
.br
.ti -1c
.RI "enum \fBMode\fP { \fBMENU_PRINCIPAL\fP, \fBSIMULATION\fP, \fBEDITION\fP, \fBCONFIGURE\fP, \fBTEST\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
INF2990 
.RE
.PP
\fBDate:\fP
.RS 4
2016-02-13 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
